config/routes.rb
Ratebeer::Application.routes.draw do
  resources :styles

  resources :memberships

  resources :beer_clubs

  resources :users

  resources :beers

  resources :breweries

  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  resources :ratings, only: [:index, :new, :create, :destroy]
  get 'signup', to: 'users#new'
  resources :sessions, only: [:new, :create]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  resources :places, only: [:index, :show]
  post 'places', to: 'places#search'

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  validates_uniqueness_of :user_id, :scope => [:beer_club_id], :message => "cant be in the same club twice"

  belongs_to :beer_club
  belongs_to :user
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
    @beer_clubs = BeerClub.all
  end

  # GET /memberships/1/edit
  def edit
    @beer_clubs = BeerClub.all
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)



    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership.beer_club, notice: "#{@membership.user.username}, welcome to the club!" }
        format.json { render action: 'show', status: :created, location: @membership }
      else
        @beer_clubs = BeerClub.all
        format.html { render action: 'new' }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:beer_club_id, :user_id)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
    <% if @membership.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@membership.errors.count, "error") %> prohibited membership from being saved:</h2>

          <ul>
            <% @membership.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.select :beer_club_id, options_from_collection_for_select(@beer_clubs, :id, :name) %>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <%= f.submit %>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render 'form' %>

app/views/memberships/index.html.erb
<h1>Listing memberships</h1>

<table>
  <thead>
    <tr>
      <th>Beer club</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= BeerClub.find(membership.beer_club_id).name %></td>
        <td><%= User.find(membership.user_id).username %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) if current_user == membership.user %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } if current_user == membership.user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to('New Membership', new_membership_path) if current_user %>

app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render 'form' %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Beer club:</strong>
  <%= BeerClub.find(@membership.beer_club_id).name %>
</p>

<p>
  <strong>User:</strong>
  <%= User.find(@membership.user_id).username %>
</p>

<%= link_to('Edit', edit_membership_path(@membership)) if current_user %>