config/routes.rb
Ratebeer::Application.routes.draw do
  resources :styles

  resources :memberships

  resources :beer_clubs

  resources :users

  resources :beers

  resources :breweries

  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  resources :ratings, only: [:index, :new, :create, :destroy]
  get 'signup', to: 'users#new'
  resources :sessions, only: [:new, :create]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  resources :places, only: [:index, :show]
  post 'places', to: 'places#search'

end

app/models/user.rb
class User < ActiveRecord::Base
  include RatingAverage

  has_secure_password

  validates :username, uniqueness: true, length: { minimum: 3 }, length: { maximum: 15 }
  validates :password, length: { minimum: 4 }, format: /\A(?=.*\d)(?=.*[A-Z]).{4,}\z/

  has_many :ratings, dependent: :destroy
  has_many :beers, -> { uniq }, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships

  def favorite_beer
    return nil if ratings.empty?
    ratings.order(score: :desc).limit(1).first.beer
  end

  # omat vanhat favorite style & favorite brewery

  #def favorite_style
  #  return nil if ratings.empty?
  #  calculate_favorite_style
  #end
  #
  #def calculate_favorite_style
  #  styles = ["Weizen", "Lager", "Pale ale", "IPA", "Porter"]
  #  favorite = nil
  #  score = -1
  #  styles.each do |style|
  #    rats = ratings.find_all { |r| r.beer.style == style }.map{ |ra| ra.score}
  #    average = rats.sum.to_f / rats.count.to_f unless rats.nil?
  #    if rats.nil?
  #    elsif average > score
  #      favorite = style
  #      score = average
  #    end
  #  end
  #  favorite
  #end
  #
  #def favorite_brewery
  #  return nil if ratings.empty?
  #  calculate_favorite_brewery
  #end
  #
  #def calculate_favorite_brewery
  #  breweries = ratings.map{ |r| r.beer.brewery }
  #  favorite = nil
  #  score = -1
  #  breweries.each do |brewery|
  #    rats = ratings.find_all { |r| r.beer.brewery == brewery }.map{ |ra| ra.score}
  #    average = rats.sum.to_f / rats.count.to_f unless rats.nil?
  #    if rats.nil?
  #    elsif average > score
  #      favorite = brewery
  #      score = average
  #    end
  #  end
  #  favorite
  #end

  # omat vanhat end

  def favorite_brewery
    return nil if ratings.empty?
    brewery_ratings = rated_breweries.inject([]) { |set, brewery| set << [brewery, brewery_average(brewery) ] }
    brewery_ratings.sort_by{ |r| r.last }.last.first
  end

  def favorite_style
    return nil if ratings.empty?
    style_ratings = rated_styles.inject([]) { |set, style| set << [style, style_average(style) ] }
    style_ratings.sort_by{ |r| r.last }.last.first
  end

  private

  def rated_styles
    ratings.map{ |r| r.beer.style }.uniq
  end

  def style_average(style)
    ratings_of_style = ratings.select{ |r| r.beer.style==style }
    ratings_of_style.inject(0.0){ |sum, r| sum+r.score}/ratings_of_style.count
  end

  def rated_breweries
    ratings.map{ |r| r.beer.brewery}.uniq
  end

  def brewery_average(brewery)
    ratings_of_brewery = ratings.select{ |r| r.beer.brewery==brewery }
    ratings_of_brewery.inject(0.0){ |sum, r| sum+r.score}/ratings_of_brewery.count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:beers, :ratings).all
    #@users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params.username.nil? and @user == current_user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user == @user
      @user.destroy
      reset_session
    end
    #Rating.where(user_id:nil).each{ |r| r.delete }
    #Rating.all.select{ |r| r.user == nil }.each{ |r| r.delete }
    #Membership.where(user_id:nil).each{ |m| m.delete }
    #Membership.all.select{ |m| m.user == nil }.each{ |m| m.delete }
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% if @user.new_record? %>
        <div class="field">
          <%= f.label :username %><br />
          <%= f.text_field :username %>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation  %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
  <th> </th>
  <th> rated beers </th>
  <th> total ratings </th>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= @user.username %></strong>
</p>

<p>
  <% if @user.ratings.empty? %>
    has not made any ratings yet
  <% else %>
      has made <%= pluralize(@user.ratings.count, 'rating') %>, average rating given
      <%= round(@user.average_rating) %>
      <br> Favorite beer:
      <%= link_to @user.favorite_beer, @user.favorite_beer %>
      <br> Favorite style:
      <%= @user.favorite_style %>
      <br> Favorite brewery:
      <%= link_to @user.favorite_brewery.name, @user.favorite_brewery %>
      <br>
      <br>
      <strong>Ratings</strong>
      <ul>
        <% @user.ratings.each do |rating| %>
            <li> <%= rating %>
              <% if @user == current_user %>
                <%= link_to 'delete', rating_path(rating.id), method: :delete, data: { confirm: 'Are you sure?' } %> </li>
              <% end %>
        <% end %>
      </ul>

  <% end %>
</p>

<p>
  <% if @user.beer_clubs.empty? %>
    does not belong to a beer club.
  <% else %>
    member of
    <% @user.beer_clubs.each do |beer_club| %>
        <%= link_to beer_club.name, beer_club %>
    <% end %>
  <% end %>
</p>

<% if @user == current_user %>
    <%= link_to 'Change password', edit_user_path(@user) %> |
    <%= link_to 'Delete account', user_path, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>