config/routes.rb
Ratebeer::Application.routes.draw do
  resources :styles

  resources :memberships

  resources :beer_clubs

  resources :users

  resources :beers

  resources :breweries

  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  resources :ratings, only: [:index, :new, :create, :destroy]
  get 'signup', to: 'users#new'
  resources :sessions, only: [:new, :create]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  resources :places, only: [:index, :show]
  post 'places', to: 'places#search'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ratebeer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="navibar">
        <%= link_to 'Breweries', breweries_path %>
        <%= link_to 'Beers', beers_path %>
        <%= link_to 'Ratings', ratings_path %>
        <%= link_to 'Users', users_path %>
        <%= link_to 'Beer clubs', beer_clubs_path %>
        <%= link_to 'Places', places_path %>
        <%= link_to 'Styles', styles_path %>
        <%= " | " %>
        <% if current_user.nil? %>
            <%= link_to 'Sign in', new_session_path %>
            <%= link_to 'Sign up', new_user_path %>
        <% else %>
            <%= link_to current_user.username, current_user %>
            <%= link_to 'Rate a beer', new_rating_path %>
            <%= link_to 'Join a club', new_membership_path %>
            <%= link_to 'Sign out', signout_path, method: :delete %>
        <% end %>
    </div>

<%= yield %>

</body>
</html>